#系统配置
server:
  port: 9999

# mongo 配置
spring:
  data:
    mongodb:
      host: 192.168.0.125
      port: 27017
      database: workflow

# 异步线程池配置
spring.async:
  corePoolSize: 10
  maxPoolSize: 30
  queueCapacity: 8
  keepAlive: 60

notify:
  telegram:
    botUserName: xxx
    token: xxx

proxy:
  host: 127.0.0.1
  port: 1080


---

spring.profiles: test